# Generated by Django 4.0 on 2021-12-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_routine_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='routine',
        ),
        migrations.AddField(
            model_name='exercise',
            name='routine',
            field=models.ManyToManyField(related_name='exercises', to='exercises.Routine'),
        ),
    ]
