# Generated by Django 4.0 on 2021-12-15 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_set_remove_exercise_reps_remove_exercise_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='set',
        ),
        migrations.AddField(
            model_name='exercise',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='exercises.set'),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercise'),
            preserve_default=False,
        ),
    ]
