# Generated by Django 4.0 on 2021-12-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_exercise_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.routine'),
        ),
    ]
