# Generated by Django 4.0 on 2021-12-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_exercise_routine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='set',
            new_name='sets',
        ),
    ]
