# Generated by Django 4.0 on 2021-12-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_rename_set_exercise_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='routine',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.workout'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AbstractExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.routine')),
            ],
        ),
    ]
